"use client";

import { Suspense } from "react";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { AlertCircle, Banknote } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { useSearchParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";

interface FeeInvoice {
  id: string;
  period_label: string;
  total_amount: number;
  status: string;
  due_date: string;
}

const statusColors: Record<string, string> = {
  unpaid: "bg-danger/10 text-danger",
  partially_paid: "bg-accent/10 text-accent",
  paid: "bg-success/10 text-success",
  overdue: "bg-danger/10 text-danger",
};

async function fetchFees(childId: string | null): Promise<FeeInvoice[]> {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return [];

  let studentId = childId;

  if (!studentId) {
    const { data: guardian } = await supabase
      .from("guardians")
      .select("id")
      .eq("auth_user_id", user.id)
      .single();

    if (!guardian) return [];

    const { data: sgList } = await supabase
      .from("student_guardians")
      .select("student_id")
      .eq("guardian_id", guardian.id)
      .limit(1);

    if (!sgList || sgList.length === 0) return [];
    studentId = sgList[0].student_id;
  }

  const { data } = await supabase
    .from("fee_invoices")
    .select("id, period_label, total_amount, status, due_date")
    .eq("student_id", studentId)
    .order("due_date", { ascending: false });

  return data || [];
}

function ParentFeesContent() {
  const searchParams = useSearchParams();
  const childId = searchParams.get("child");

  const { data: invoices = [], isLoading: loading, error } = useQuery<FeeInvoice[]>({
    queryKey: ["parent-fees", childId],
    queryFn: () => fetchFees(childId),
    enabled: !!childId,
  });

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center">
        <AlertCircle className="h-10 w-10 text-danger mb-3" />
        <p className="text-sm font-medium text-ink">Failed to load data</p>
        <p className="text-xs text-slate mt-1">{error.message}</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <PageHeader title="Fees" description="View and pay your child's fees" />

      {loading ? (
        <div className="space-y-2">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-16 bg-paper-raised rounded-lg animate-skeleton" />
          ))}
        </div>
      ) : invoices.length === 0 ? (
        <EmptyState icon={Banknote} title="No fee invoices" description="Fee invoices will appear here once generated by your school." />
      ) : (
        <div className="space-y-3">
          {invoices.map((inv) => (
            <div key={inv.id} className="bg-paper-raised rounded-xl border border-slate-light p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium text-ink">{inv.period_label}</p>
                  <p className="text-xs text-slate">
                    Due: {new Date(inv.due_date).toLocaleDateString("en-GB")}
                  </p>
                </div>
                <div className="text-right">
                  <p className="font-bold text-ink tabular-nums">
                    PKR {Number(inv.total_amount).toLocaleString()}
                  </p>
                  <span
                    className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium capitalize ${
                      statusColors[inv.status] || "bg-slate/10 text-slate"
                    }`}
                  >
                    {inv.status.replace("_", " ")}
                  </span>
                </div>
              </div>
              {inv.status !== "paid" && (
                <Button size="sm" className="mt-3 bg-accent hover:bg-accent/90 text-white">
                  Pay now
                </Button>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default function ParentFees() {
  return (
    <Suspense fallback={
      <div className="space-y-2">
        {[1, 2, 3].map((i) => (
          <div key={i} className="h-16 bg-paper-raised rounded-lg animate-skeleton" />
        ))}
      </div>
    }>
      <ParentFeesContent />
    </Suspense>
  );
}
