"use client";

import { useState, useEffect } from "react";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Banknote } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

interface FeeInvoice {
  id: string;
  period_label: string;
  total_amount: number;
  status: string;
  due_date: string;
}

const statusColors: Record<string, string> = {
  unpaid: "bg-danger/10 text-danger",
  partially_paid: "bg-accent/10 text-accent",
  paid: "bg-success/10 text-success",
  overdue: "bg-danger/10 text-danger",
};

export default function ParentFees() {
  const [invoices, setInvoices] = useState<FeeInvoice[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      const supabase = createClient();
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const { data: guardian } = await supabase
        .from("guardians")
        .select("id")
        .eq("auth_user_id", user.id)
        .single();

      if (!guardian) { setLoading(false); return; }

      const { data: sg } = await supabase
        .from("student_guardians")
        .select("student_id")
        .eq("guardian_id", guardian.id)
        .limit(1)
        .single();

      if (!sg) { setLoading(false); return; }

      const { data } = await supabase
        .from("fee_invoices")
        .select("id, period_label, total_amount, status, due_date")
        .eq("student_id", sg.student_id)
        .order("due_date", { ascending: false });

      setInvoices(data || []);
      setLoading(false);
    }
    load();
  }, []);

  return (
    <div className="space-y-6">
      <PageHeader title="Fees" description="View and pay your child's fees" />

      {loading ? (
        <div className="space-y-2">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-16 bg-paper-raised rounded-lg animate-skeleton" />
          ))}
        </div>
      ) : invoices.length === 0 ? (
        <EmptyState icon={Banknote} title="No fee invoices" description="Fee invoices will appear here once generated by your school." />
      ) : (
        <div className="space-y-3">
          {invoices.map((inv) => (
            <div key={inv.id} className="bg-paper-raised rounded-xl border border-slate-light p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium text-ink">{inv.period_label}</p>
                  <p className="text-xs text-slate">
                    Due: {new Date(inv.due_date).toLocaleDateString("en-PK")}
                  </p>
                </div>
                <div className="text-right">
                  <p className="font-bold text-ink tabular-nums">
                    PKR {Number(inv.total_amount).toLocaleString()}
                  </p>
                  <span
                    className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium capitalize ${
                      statusColors[inv.status] || "bg-slate/10 text-slate"
                    }`}
                  >
                    {inv.status.replace("_", " ")}
                  </span>
                </div>
              </div>
              {inv.status !== "paid" && (
                <Button size="sm" className="mt-3 bg-accent hover:bg-accent/90 text-white">
                  Pay now
                </Button>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
